import 'package:json_annotation/json_annotation.dart';

/// {@template torrent_sort}
/// Torrent sort.
/// {@endtemplate}
enum TorrentSort {
  @JsonValue('added_on')
  addedOn,
  @JsonValue('amount_left')
  amountLeft,
  @JsonValue('auto_tmm')
  autoTmm,
  @JsonValue('availability')
  availability,
  @JsonValue('category')
  category,
  @JsonValue('completed')
  completed,
  @JsonValue('completion_on')
  completionOn,
  @JsonValue('content_path')
  contentPath,
  @JsonValue('dl_limit')
  dlLimit,
  @JsonValue('dlspeed')
  dlSpeed,
  @JsonValue('downloaded')
  downloaded,
  @JsonValue('downloaded_session')
  downloadedSession,
  @JsonValue('eta')
  eta,
  @JsonValue('f_l_piece_prio')
  fLPiecePrio,
  @JsonValue('force_start')
  forceStart,
  @JsonValue('hash')
  hash,
  @JsonValue('last_activity')
  lastActivity,
  @JsonValue('magnet_uri')
  magnetUri,
  @JsonValue('max_ratio')
  maxRatio,
  @JsonValue('max_seeding_time')
  maxSeedingTime,
  @JsonValue('name')
  name,
  @JsonValue('num_complete')
  numComplete,
  @JsonValue('num_incomplete')
  numIncomplete,
  @JsonValue('num_leechs')
  numLeechs,
  @JsonValue('num_seeds')
  numSeeds,
  @JsonValue('priority')
  priority,
  @JsonValue('progress')
  progress,
  @JsonValue('ratio')
  ratio,
  @JsonValue('ratio_limit')
  ratioLimit,
  @JsonValue('save_path')
  savePath,
  @JsonValue('seeding_time')
  seedingTime,
  @JsonValue('seeding_time_limit')
  seedingTimeLimit,
  @JsonValue('seen_complete')
  seenComplete,
  @JsonValue('seq_dl')
  seqDl,
  @JsonValue('size')
  size,
  @JsonValue('state')
  state,
  @JsonValue('super_seeding')
  superSeeding,
  @JsonValue('tags')
  tags,
  @JsonValue('time_active')
  timeActive,
  @JsonValue('total_size')
  totalSize,
  @JsonValue('tracker')
  tracker,
  @JsonValue('up_limit')
  upLimit,
  @JsonValue('uploaded')
  uploaded,
  @JsonValue('uploaded_session')
  uploadedSession,
  @JsonValue('upspeed')
  upSpeed
}
