enum TorrentSort {
  addedOn('added_on'),
  amountLeft('amount_left'),
  autoTmm('auto_tmm'),
  availability('availability'),
  category('category'),
  completed('completed'),
  completionOn('completion_on'),
  contentPath('content_path'),
  dlLimit('dl_limit'),
  dlSpeed('dlspeed'),
  downloaded('downloaded'),
  downloadedSession('downloaded_session'),
  eta('eta'),
  fLPiecePrio('f_l_piece_prio'),
  forceStart('force_start'),
  hash('hash'),
  lastActivity('last_activity'),
  magnetUri('magnet_uri'),
  maxRatio('max_ratio'),
  maxSeedingTime('max_seeding_time'),
  name('name'),
  numComplete('num_complete'),
  numIncomplete('num_incomplete'),
  numLeechs('num_leechs'),
  numSeeds('num_seeds'),
  priority('priority'),
  progress('progress'),
  ratio('ratio'),
  ratioLimit('ratio_limit'),
  savePath('save_path'),
  seedingTime('seeding_time'),
  seedingTimeLimit('seeding_time_limit'),
  seenComplete('seen_complete'),
  seqDl('seq_dl'),
  size('size'),
  state('state'),
  superSeeding('super_seeding'),
  tags('tags'),
  timeActive('time_active'),
  totalSize('total_size'),
  tracker('tracker'),
  upLimit('up_limit'),
  uploaded('uploaded'),
  uploadedSession('uploaded_session'),
  upSpeed('upspeed');

  const TorrentSort(this.value);

  final String value;
}
